name: Test Go

on: 
  push:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum  
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: "go.mod"

    - name: Test
      run: go test -v ./...